version: "3"

services:
  redis:
    image: redis

  cli:
    image: ${SYSROOT_CLI_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - .:/code/faasm-toolchain
      - ./build:/build/faasm-toolchain
    working_dir: /code/faasm-toolchain
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis
